name: React + Vite CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs: 
  build: 
    name: Build client
    runs-on: ubuntu-latest

    steps: 
      - name: Pull code to VM Github
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
  test:
    name: Test Client
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Test echo
        run: echo 'Test success'
     

    
